### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by hvddrift** [vector76/gridfinity_openscad#14]
Re your socket modules. Mine only has one parameter. Should there be more? If not how does it work?

For example if I have a socket set that is 

26mm, 25mm, 23mm, 22mm, 17mm etc in diameter can I create a print to suit?

**Comment by vector76** [comment]
I had use a single parameter ("part") to generate a small number of variants from a single file, and to generate a custom one you would need to edit the code.

I think you could create what you want by defining part to be 100 or something and then add something like this:
`socket_holder(3, [26,25,23,17], "Custom");`

The first number (3 in this case) is the number of gridfinity units, and the list [26,25,23,17] specifies the number of sockets and their sizes.  The string "Custom" is added as a label and can be whatever you want.

So that should be how you customize it, however, it does look like there is a collision for sockets larger than 24mm and it won't fit properly.  (You can see the red cylinders poking through the model.)

![image](https://user-images.githubusercontent.com/955138/188223813-2917143f-3e80-470b-ac20-e8311ae8f99f.png)

If you lower the height by using `num_z` of about 2.3, it looks like it will clear:

![image](https://user-images.githubusercontent.com/955138/188224312-7b8e3255-9e05-4ec6-8fe6-85c79be89bde.png)

Hope that helps!
